[package]
name = "grainiac_core"
version = "0.1.0"
edition = "2021"

[dependencies]
fastrand = "2.3.0"
rtsan-standalone = "0.1.1"
triple_buffer = "8.1.1"

[features]
rtsan = ["rtsan-standalone/enable"]
