[package]
name = "grainiac_tui"
version = "0.1.0"
edition = "2021"

[dependencies]
jack = "0.13.0"
grainiac_core = { path = "../grainiac_core" }
ratatui = "0.29.0"
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
crossbeam = "0.8.4"
hound = "3.5.1"
